# Changes here will be overwritten by Copier
_commit: v0.1.0
_src_path: gh:xonsh/xontrib-template
email: no@no.no
enable_autoloading: false
enable_pre_commit_hooks: true
full_name: xontrib-fish-completer
github_username: xonsh
has_aliases: false
has_events: false
package_manager: setuptools
project_name: fish-completer
project_package_name: fish_completer
project_repo_name: xontrib-fish-completer
project_short_description: Populate rich completions using fish and remove the default
    bash based completer.
pure_py: true
py_module_name: xontrib_fish_completer
version: 0.0.1

